-- Project Euler Problem 29.

-- How many distinct terms are in the sequence generated by a^b for 2 <= a <=
-- 100 and 2 <= b <= 100?

local MIN, MAX = 2, 100 -- 100 was not a problem for native Lua.

-- Again, brute force.
local a2b_distinct_count = 0
local a2b_present = {}

for a = MIN, MAX do
   for b = MIN, MAX do
      local a2b = a ^ b
      if not a2b_present[a2b] then
         a2b_present[a2b] = true
         a2b_distinct_count = a2b_distinct_count + 1
      end
   end
end

print(a2b_distinct_count)
-- 9183
